package org.jbpm.rest_task;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class Bar  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String name;
    
    @org.kie.api.definition.type.Position(value = 0)
    private org.jbpm.rest_task.Zap zap;

    public Bar() {
    }

    public Bar(org.jbpm.rest_task.Zap zap, java.lang.String name) {
        this.zap = zap;
        this.name = name;
    }


    
    public java.lang.String getName() {
        return this.name;
    }

    public void setName(  java.lang.String name ) {
        this.name = name;
    }
    
    public org.jbpm.rest_task.Zap getZap() {
        return this.zap;
    }

    public void setZap(  org.jbpm.rest_task.Zap zap ) {
        this.zap = zap;
    }
}