package org.jbpm.rest_task;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class Zap  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer id;

    public Zap() {
    }

    public Zap(java.lang.Integer id) {
        this.id = id;
    }


    
    public java.lang.Integer getId() {
        return this.id;
    }

    public void setId(  java.lang.Integer id ) {
        this.id = id;
    }
}